#ifndef MYGANTT_GLOBALVALUES
#define MYGANTT_GLOBALVALUES


#define GANTTSCENE_MIN_WIDTH (300)
#define GANTTGRAPHICSVIEW_MIN_WIDTH (GANTTSCENE_MIN_WIDTH)
#define GANTTTREEVIEW_MIN_WIDTH (200)

#define DEFAULT_ITEM_WIDTH      (qreal(20))
#define DEFAULT_MONTH_WIDTH     (qreal(35))

#define DEFAULT_ITEM_HEIGHT     (qreal(20))
#define DEFAULT_HEADER_HEIGHT    (2*DEFAULT_ITEM_HEIGHT)


//the three values below are dependent
#define MIN_WIDTH_FOR_TIME_VISUALIZING (qreal(30)) // in pixels
#define LITTLE_HATCH_COUNT (5)
#define MIN_DISTANCE_BETWEEN_HATCHES (qreal(5))

#define HOURS_IN_DAY (24)
#define MINUTS_IN_HOUR (60)
#define SECONDS_IN_MINUTE (60)
#define _MILISECONDS_IN_SECOND (1000)
#define _MICROSECONDS_IN_MILISECOND (1000)

#define _MICROSECONDS_IN_SECOND (1000000)


#define SECONDS_IN_HOUR (3600)
#define SECONDS_IN_DAY (86400)

#endif // MYGANTT_GLOBALVALUES

